mode: deployment

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
    prometheus:
      config:
        scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 10s
            static_configs:
              - targets: [ '0.0.0.0:8888' ]

  processors:
    batch: {}
    attributes:
      actions:
        - action: insert
          key: loki.attribute.labels
          value: container
        - action: insert
          key: loki.format
          value: raw

  exporters:
    prometheusremotewrite:
      endpoint: "prometheus-server.prometheus.svc.cluster.local:80"
    logging:
      loglevel: debug
    otlp:
      endpoint: "tempo-distributor.tempo.svc.cluster.local:4317"
      tls:
        insecure: true
    loki:
      endpoint: "loki-gateway.loki.svc.cluster.local:3100/loki/api/v1/push"
      tls:
        insecure: true  # Set to true if Loki uses an insecure connection (HTTP)

  service:
    telemetry:
      logs:
        level: "debug"
      metrics:
        address: ":8888"
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging, otlp]
      metrics:
        receivers: [prometheus]
        processors: [batch]
        exporters: [logging, prometheusremotewrite]
      logs:
        receivers: [otlp]
        processors: [batch, attributes]
        exporters: [logging, loki]

