---
storage:
  trace:
    backend: s3
    s3:
      access_key: ${{ secrets.TEMPO_USER }}
      secret_key: ${{ secrets.TEMPO_PASS }}
      bucket: 'tempo-traces'
      endpoint: 'tempo-minio:9000'
      insecure: true
#MinIO storage configuration
minio:
  enabled: true
  mode: standalone
  rootUser: ${{ secrets.TEMPO_USER }}
  rootPassword: ${{ secrets.TEMPO_PASS }}
  buckets:
    # Default Tempo storage bucket
    - name: tempo-traces
      policy: none
      purge: false
traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false
